# The Docker image that will be used to build your app
image: node:alpine3.15
# Functions that should be executed before the build script is run
before_script:
  - npm install
  - npm run build
  - npm install -g serve
  - npm install -g serve
  - serve -s build
pages:
  script:
    - mv build public
    - cp public/index.html public/404.html
    - serve -s build -l 4000
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
